name: Kevin Chan

permalink: /:categories/:title

markdown: kramdown
pygments: true

navigation:
- text: "Home"
  url: "/"
- text: "About"
  url: "/about"
- text: "Projects"
  url: "/projects"
- text: "Resources"
  url: "/resources"
- text: "Contact"
  url: "/contact"


